#! /usr/bin/env sh
./gradlew asciidoctor
rm -rf ./src/main/resources/asciidoc
mkdir -p ./src/main/resources/asciidoc/
cp -f ./build/docs/asciidoc/api.html ./src/main/resources/asciidoc/apidoc.html
chmod +x ./gradlew && ./gradlew clean build --no-build-cache
