name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check add and build docker image.
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ADDRESS: ${{ secrets.DOCKER_ADDRESS }}
          DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
        run: |
          chmod +x ./gradlew && ./gradlew clean build --no-build-cache
          time=$(date "+%Y%m%d")
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
          docker build -t $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$time . && docker push $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$time
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ADDRESS: ${{ secrets.DOCKER_ADDRESS }}
          TARGET_MACHINE: ${{ secrets.TARGET_MACHINE }}
          DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME }}
          DEMO_DB_USERNAME: ${{secrets.DEMO_DB_USERNAME }}
          DEMO_DB_PASSWORD: ${{secrets.DEMO_DB_PASSWORD }}
        run: |
          sudo tee /home/id_rsa <<- EOF
          $DEPLOY_KEY
          EOF
          ssh -i /home/id_rsa $TARGET_MACHINE -o "StrictHostKeyChecking no" "docker rm -f predictor.backend"
          ssh -i /home/id_rsa $TARGET_MACHINE -o "StrictHostKeyChecking no" "docker pull $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$(date "+%Y%m%d")"
          ssh -i /home/id_rsa $TARGET_MACHINE -o "StrictHostKeyChecking no" "docker run --name predictor.backend -d -p 21000:8080 -e spring.profiles.active=demo -e spring.data.mongodb.username=$DEMO_DB_USERNAME -e spring.data.mongodb.password=$DEMO_DB_PASSWORD --restart always $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$(date "+%Y%m%d")"
