name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run integration tests
        run: sh ./scripts/check-all
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ADDRESS: ${{ secrets.DOCKER_ADDRESS }}
          DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
        run: |
          chmod +x ./gradlew && ./gradlew build --no-build-cache
          time=$(date "+%Y%m%d")
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
          docker build -t $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$time . && docker push $DOCKER_ADDRESS/$DOCKER_REPO_NAME:$time
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: echo hello
